DATA:
  dataset: PRISM #RefGraspNet # LIBERO-SPATIAL # #RefGraspNet #OCID-VLG #RefGraspNet # # #OCID-VLG # #OCID-VLG
  root_path: /data/vineet/data/ #/hdddata/vineet/RefGraspNet/ # #/data/vineet/data/RefGraspNet/ #/data/vineet/data/OCID-VLG # # #/data/vineet/data/RefGraspNet/ #/data/vineet/data/OCID-VLG #/data/vineet/data/roborefit/ #
  train_split: train
  val_split: test
TRAIN:
  # Base Arch
  use_max_pool: False
  clip_pretrain: exp/pretrain_clip/RN50.pt
  version: multiple
  input_size: 416
  word_len: 17
  word_dim: 1024
  vis_dim: 512
  fpn_in: [512, 1024, 1024]
  fpn_out: [256, 512, 1024]
  sync_bn: True
  # Decoder
  num_layers: 3
  num_head: 8
  dim_ffn: 2048
  dropout: 0.1
  intermediate: False
  # Training Setting
  workers: 1  # data loader workers
  workers_val: 2
  epochs: 50
  milestones: [35]
  start_epoch: 0
  batch_size: 18  # batch size for training. Dividied by number of GPUs used. 
  batch_size_val: 12  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001 # 0.0001
  lr_decay: 0.1
  lr_multi: 0.1
  weight_decay: 0.
  max_norm: 0.
  manual_seed: 0
  print_freq: 100
  # Resume & Save
  exp_name: CROG_PRISM
  output_folder: exp/PRISM
  save_freq: 1
  weight:  # path to initial weight (default: none)
  resume: #exp/RefGraspNet/CROG_Baseline/last_model.pth
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  # Ablation study
  use_contrastive: True
  use_pretrained_clip: True
  use_grasp_masks: True
Distributed:
  dist_url: tcp://localhost:3687
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
TEST:
  test_split: val # or test_unseen for RefGraspNet
  visualize: True